paradedb/charts

charts/cluster/artifacthub-repo.yml
This enables verified publisher status on ArtifactHub
=> chore: Create artifacthub-repo.yml

charts/paradedb-cluster/Chart.yaml, charts/paradedb-cluster/README.md, charts/paradedb-cluster/README.md.gotmpl
=> README.gotmpl

README.md, charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/README.md.gotmpl, charts/paradedb/examples/paradedb.yaml, charts/paradedb/prometheus_rules/cluster-ha-critical.yaml, charts/paradedb/prometheus_rules/cluster-ha-warning.yaml, charts/paradedb/prometheus_rules/cluster-high_connection-critical.yaml, charts/paradedb/prometheus_rules/cluster-high_connection-warning.yaml, charts/paradedb/prometheus_rules/cluster-high_replication_lag.yaml, charts/paradedb/prometheus_rules/cluster-instances_on_same_node.yaml, charts/paradedb/prometheus_rules/cluster-low_disk_space-critical.yaml, charts/paradedb/prometheus_rules/cluster-low_disk_space-warning.yaml, charts/paradedb/prometheus_rules/cluster-offline.yaml, charts/paradedb/prometheus_rules/cluster-zone_spread-warning.yaml, charts/paradedb/test/paradedb-minio-backup-restore/07-recovery_backup_pitr_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/chainsaw-test.yaml, charts/paradedb/values.yaml
=> chore: Final Cleanup

charts/paradedb/templates/_helpers.tpl
Merge this after: paradedb/paradedb/pull/1678
Otherwise the tests will fail.
=> Using the default UID/GID 999 from the postgres docker image

.github/workflows/paradedb-test-eks.yml, charts/paradedb/templates/_bootstrap.tpl
It wasn't being used or documented and was bloating our images.
=> Rm pgvectorscale

.github/workflows/check-typo.yml, .github/workflows/tests-cluster-chainsaw.yaml, charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-minio-backup-restore/02-paradedb_write.yaml, charts/paradedb/test/paradedb-minio-backup-restore/03-paradedb_test.yaml, charts/paradedb/values.yaml
=> chore: Use the new 0.11.0 release

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/README.md.gotmpl, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/templates/cluster.yaml, charts/paradedb/values.yaml
=> Fixed cron database name

charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/values.yaml
- Closes #N/A
This will ensure they don't break when we do upgrades.
=> chore: Hardcode version in ParadeDB tests

charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/values.yaml
=> feat: Default to PG17 again

charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/templates/cluster.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-enterprise/02-paradedb_test.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/values.yaml
=> feat: Prod promotion

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/values.yaml
- Closes #N/A
This can be merged once the release is out.
^
^
^
=> chore: Upgrade to 0.15.0

charts/paradedb/test/scheduledbackups/00-minio_cleanup-assert.yaml, charts/paradedb/test/scheduledbackups/00-minio_cleanup.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster-assert.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/test/scheduledbackups/chainsaw-test.yaml
- Closes #N/A
It was fixed upstream, so we can bring this in too.
^
^
^
=> feat: Add ScheduledBackups Test

charts/paradedb/templates/_bootstrap.tpl
- Closes #N/A
Required for our LR efforts.
^
^
^
=> feat: Expose many externalClusters

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.3

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/templates/cluster.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.6

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/templates/cluster.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Release 0.15.7

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/templates/cluster.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Prod Promotion -- v0.15.7

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.8

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.9

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Phil/0.15.11

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.12

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.12 (#95)

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.13

charts/paradedb/templates/user-metrics.yaml, charts/paradedb/test/monitoring/01-monitoring_cluster-assert.yaml, charts/paradedb/test/monitoring/01-monitoring_cluster.yaml
=> feat: custom monitoring query advanced configuration options

.github/workflows/paradedb-publish-chart.yml, charts/paradedb/Chart.yaml
=> fix: incorrectly referring to version as appVersion

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.14

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.15

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.16

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/postgresql-cluster-configuration/02-recovery_object_store_database_owner-assert.yaml, charts/paradedb/test/postgresql-cluster-configuration/03-recovery_backup_database_owner-assert.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.17

charts/paradedb/templates/cluster.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster-assert.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml
=> feat: Hot standy feedback

charts/paradedb/Chart.yaml, charts/paradedb/README.md, charts/paradedb/examples/image-catalog-ref.yaml, charts/paradedb/examples/image-catalog.yaml, charts/paradedb/examples/paradedb.yaml, charts/paradedb/templates/cluster.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster-assert.yaml, charts/paradedb/test/paradedb-enterprise/01-paradedb-NCC-1701-D_cluster.yaml, charts/paradedb/test/paradedb-minio-backup-restore/01-paradedb_cluster.yaml, charts/paradedb/test/scheduledbackups/01-scheduledbackups_cluster.yaml, charts/paradedb/values.yaml
=> feat: Upgrade to 0.15.18

.github/CODEOWNERS
=> docs: Added Itay as a codeowner

charts/paradedb/README.md, charts/paradedb/templates/databases.yaml, charts/paradedb/test/database-management/01-database-parameters-assert.yaml, charts/paradedb/test/database-management/01-database-parameters.yaml, charts/paradedb/test/database-management/02.1-extension-upgrade-init-assert.yaml, charts/paradedb/test/database-management/02.1-extension-upgrade-init.yaml, charts/paradedb/test/database-management/02.2-paradedb_extension_check-assert.yaml, charts/paradedb/test/database-management/02.2-paradedb_extension_check.yaml, charts/paradedb/test/database-management/02.3-extension-upgrade-post-assert.yaml, charts/paradedb/test/database-management/02.3-extension-upgrade-post.yaml, charts/paradedb/test/database-management/02.4-paradedb_extension_check-assert.yaml, charts/paradedb/test/database-management/02.4-paradedb_extension_check.yaml, charts/paradedb/test/database-management/chainsaw-test.yaml, charts/paradedb/values.schema.json, charts/paradedb/values.yaml
=> feat: Database and extension management

charts/paradedb/templates/databases.yaml, charts/paradedb/test/database-management/01-database-parameters-assert.yaml, charts/paradedb/test/database-management/01-database-parameters.yaml
=> fix: Database CR name should not contain underscores
